export const SUBMISSION_SITE_URL: string;

export function slugify(value: string): string;
export function normalizeSubmissionFields(
  fields?: Record<string, unknown>,
): Record<string, string>;
export function buildPrDraftFromSpec(
  spec: Record<string, unknown>,
  fields?: Record<string, unknown>,
): Record<string, unknown>;
export function buildSubmissionUrlsFromSpec(
  spec: Record<string, unknown>,
  args?: Record<string, unknown>,
): Record<string, unknown>;
export function getSubmissionSchemaFromSpec(
  spec: Record<string, unknown>,
  args?: Record<string, unknown>,
): Record<string, unknown>;
export function validateSubmissionDraftFromSpec(
  spec: Record<string, unknown>,
  args?: Record<string, unknown>,
): Record<string, unknown>;
export function prepareSubmissionDraftFromSpec(
  spec: Record<string, unknown>,
  args?: Record<string, unknown>,
): Record<string, unknown>;
export function getSubmissionExamplesFromSpec(
  spec: Record<string, unknown>,
  args?: Record<string, unknown>,
): Record<string, unknown>;
export function reviewSubmissionDraftFromSpec(
  spec: Record<string, unknown>,
  args?: Record<string, unknown>,
  entries?: Array<Record<string, unknown>>,
): Record<string, unknown>;
export function searchDuplicateEntries(
  entries?: Array<Record<string, unknown>>,
  args?: Record<string, unknown>,
): Record<string, unknown>;
export function getCategorySubmissionGuidanceFromSpec(
  spec: Record<string, unknown>,
  args?: Record<string, unknown>,
): Record<string, unknown>;
